#deployment of comments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1 #Running pods
  selector: # selector and metadata working together => selector say to the deployment what pods it need to mange
    matchLabels:
      app: comments #seek the identify call "comments"
  template: #actual create the pods
    metadata:
      labels: #the identify of the pod
        app: comments
    spec:
      containers:
        - name: comments
          image: eyalpross101/comments ##latest ==> when run kubectl rollout restart deployment comments-depl its take the latest version from docker hub
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001 #open port 4001 on the node
      targetPort: 4001 #direct the traffic inside the node to port 4001

