apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/* #Any change made in this folder will cause a change in the cluster
build:
  local:
    push: false #when skaffel make change of image he try as default to push to docker hub , we disable this option
  artifacts:
    - image: eyalpross101/client #Will try to bring any change in the client folder to the pod as soon as it happens
      context: client
      sync:
        manual:
          - src: src/**/*.js #seek change of js files
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: eyalpross101/comments #Will try to bring any change in the comments folder to the pod as soon as it happens
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js" #seek change of js files
            dest: .
    - image: eyalpross101/event-bus #Will try to bring any change in the event-bus folder to the pod as soon as it happens
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js" #seek change of js files
            dest: .

    - image: eyalpross101/moderation #Will try to bring any change in the moderation folder to the pod as soon as it happens
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js" #seek change of js files
            dest: .
    - image: eyalpross101/posts #Will try to bring any change in the posts folder to the pod as soon as it happens
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js" #seek change of js files
            dest: .
    - image: eyalpross101/query #Will try to bring any change in the query folder to the pod as soon as it happens
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js" #seek change of js files
            dest: .
