#service of posts
apiVersion: v1
kind: Service
metadata:
  name: posts-srv #name of service =>open connection from outside app (for dev)
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 #open port 4000 on the node
      targetPort: 4000 #direct the traffic inside the node to port 4000
